CREATE TABLE IF NOT EXISTS public.job_search (
  "ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company text,
  role text,
  found_at timestamp without time zone,
  link text,
  full_description text
);

ALTER TABLE public.job_search
  ALTER COLUMN company TYPE text USING company::text,
  ALTER COLUMN role TYPE text USING role::text,
  ALTER COLUMN link TYPE text USING link::text;
